
package ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BanqueService", targetNamespace = "http://ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanqueService {


    /**
     * 
     * @param montant
     * @return
     *     returns double
     */
    @WebMethod(operationName = "ConvertEurotoDH")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ConvertEurotoDH", targetNamespace = "http://ws/", className = "ws.ConvertEurotoDH")
    @ResponseWrapper(localName = "ConvertEurotoDHResponse", targetNamespace = "http://ws/", className = "ws.ConvertEurotoDHResponse")
    @Action(input = "http://ws/BanqueService/ConvertEurotoDHRequest", output = "http://ws/BanqueService/ConvertEurotoDHResponse")
    public double convertEurotoDH(
        @WebParam(name = "montant", targetNamespace = "")
        double montant);

    /**
     * 
     * @return
     *     returns java.util.List<ws.Compte>
     */
    @WebMethod(operationName = "ListedesCompteBnacaire")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ListedesCompteBnacaire", targetNamespace = "http://ws/", className = "ws.ListedesCompteBnacaire")
    @ResponseWrapper(localName = "ListedesCompteBnacaireResponse", targetNamespace = "http://ws/", className = "ws.ListedesCompteBnacaireResponse")
    @Action(input = "http://ws/BanqueService/ListedesCompteBnacaireRequest", output = "http://ws/BanqueService/ListedesCompteBnacaireResponse")
    public List<Compte> listedesCompteBnacaire();

    /**
     * 
     * @param codeBanque
     * @return
     *     returns ws.Compte
     */
    @WebMethod(operationName = "CompteBancaire")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "CompteBancaire", targetNamespace = "http://ws/", className = "ws.CompteBancaire")
    @ResponseWrapper(localName = "CompteBancaireResponse", targetNamespace = "http://ws/", className = "ws.CompteBancaireResponse")
    @Action(input = "http://ws/BanqueService/CompteBancaireRequest", output = "http://ws/BanqueService/CompteBancaireResponse")
    public Compte compteBancaire(
        @WebParam(name = "CodeBanque", targetNamespace = "")
        Long codeBanque);

}
